name: ReactCI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

 
      - name: Build and Push Frontend
        uses: docker/build-push-action@v3
        with:
          file: ./client/Dockerfile 
          push: true
          tags: TIPPATAI-KONGPAYUNG/numerical:last
       


      - name: Build and Push Backend
        uses: docker/build-push-action@v3
        with:
          file: ./server/Dockerfile 
          push: true
          tags: TIPPATAI-KONGPAYUNG/numerical:last
         
